services:

  db:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: postgres
      POSTGRES_DB: minitwit
    volumes:
      - minitwit_db:/var/lib/postgresql/data
    networks:
      - minitwit

  web:
    build:
      context: .
      dockerfile: docker/webserver.Dockerfile
    depends_on:
      - db
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: postgres
      POSTGRES_DB: minitwit 
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - minitwit
      
networks:
  minitwit: {}

volumes:
  minitwit_db: {}