services:

  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: postgres
      POSTGRES_DB: minitwit
    volumes:
      - ./local/pgdata:/var/lib/postgresql/data
    networks:
      - minitwit

  web:
    image: minitwit:database
    depends_on:
      - db
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: postgres
      POSTGRES_DB: minitwit
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - minitwit
      
networks:
  minitwit: {}