services:

  db:
    image: antonfolkmann/minitwitdb:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: postgres
      POSTGRES_DB: minitwit
    volumes:
      - minitwit_db:/var/lib/postgresql/data
    networks:
      - minitwit

  web:
    image: antonfolkmann/minitwit:latest
    container_name: minitwit
    depends_on:
      - db
      - grafana
      - prometheus
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: postgres
      POSTGRES_DB: minitwit 
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - minitwit

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - minitwit

  grafana:
    image: grafana/grafana:4.5.2
    ports:
      - "3000:3000"  
    networks:
      - minitwit 
      
networks:
  minitwit: {}

volumes:
  minitwit_db: {}