@startuml

database PostgreSQL
component GORM
component Services
component Controllers
component Frontend
component Simulator
() HTTP
() "SQL Driver" as SQLDriver

Frontend -down-( HTTP
Simulator -down-( HTTP
Controllers -up- HTTP

Controllers ..> Services
Services ..> GORM

GORM -down-( SQLDriver
PostgreSQL -up- SQLDriver

@enduml