name: Build LaTeX document

on: 
  workflow_dispatch:
  release:
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: _main.tex
          working_directory: report
          
      - uses: actions/upload-artifact@v3
        with:
          name: FinalReport
          path: report/_main.pdf # or path/to/artifact
