name: Build LaTeX document

on: 
  workflow_dispatch:
  release:
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: _main.tex
          working_directory: report
          
      - name: move pdf
        run: |
          mkdir build
          mv _main.pdf build/_main.pdf
        working-directory: report

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add report/build/_main.pdf
          git commit -m "Added report"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: main
          force: true
